# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10video_data.proto\"o\n\tVideoData\x12\x11\n\tvideo_url\x18\x01 \x01(\t\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\x12\x18\n\x10publication_date\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\tb\x06proto3')



_VIDEODATA = DESCRIPTOR.message_types_by_name['VideoData']
VideoData = _reflection.GeneratedProtocolMessageType('VideoData', (_message.Message,), {
  'DESCRIPTOR' : _VIDEODATA,
  '__module__' : 'video_data_pb2'
  # @@protoc_insertion_point(class_scope:VideoData)
  })
_sym_db.RegisterMessage(VideoData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEODATA._serialized_start=20
  _VIDEODATA._serialized_end=131
# @@protoc_insertion_point(module_scope)
